export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";

export const REQUEST_EMPLOYEES_PENDING = "REQUEST_EMPLOYEES_PENDING";
export const REQUEST_EMPLOYEES_SUCCESS = "REQUEST_EMPLOYEES_SUCCESS";
export const REQUEST_EMPLOYEES_FAILED = "REQUEST_EMPLOYEES_FAILED";
